Add `CGColorSpace` type
gfx-rs/metal-rs pull request #242
Opened 2022-09-05 07:40 UTC by jinleili

Prepare to add color space to wgpu

2022-09-20 07:02 UTC, cwfitzgerald requested changes
Looking good, some comments.

2022-09-20 07:02 UTC, cwfitzgerald commented on src/color_space.rs
> +    static kCGColorSpaceITUR_2020_HLG: CFStringRef;
Let's get rid of these, There's no difference between these and the 2100 ones, the 2020 ones were just mildly incorrectly named.

2022-09-20 07:02 UTC, cwfitzgerald commented on src/color_space.rs
> +    static kCGColorSpaceLinearITUR_2020: CFStringRef;
We seem to be missing https://developer.apple.com/documentation/coregraphics/cgcolorspace/3892090-itur_2020_srgbgamma, which does come up

2022-09-21 17:57 UTC, madsmtm reviewed
Just noting: Somewhat duplicate of what's in https://github.com/servo/core-foundation-rs/blob/de8752262a2f4a253c8c0f214294094c28e9c0ba/core-graphics/src/color_space.rs

2022-09-22 02:28 UTC, jinleili commented
Yes, but metal-rs currently does not directly depend on `core-graphics` crate, just `core-graphics-types`

2023-04-15 06:21 UTC, AlexanderEkdahl commented
@jinleili I added these color spaces in https://github.com/servo/core-foundation-rs/pull/533 which would allow your implementation to use extended range rendering if you depend on `core-graphics`.

2023-04-16 21:06 UTC, closed without merging