Documentation generation
gfx-rs/metal-rs pull request #250
Opened 2022-12-10 16:42 UTC by IsaccBarker

See issue #5, specifically [here](https://github.com/gfx-rs/metal-rs/issues/5#issuecomment-1345299215).

GitHub Pages still has to be set up via repository settings, but this should work. It worked on [my fork](https://isaccbarker.github.io/metal-rs/metal/).

2022-12-26 06:51 UTC, kvark commented
@IsaccBarker thank you! What changes need to be done, exactly? Pages enabled in what way?

2022-12-26 06:55 UTC, IsaccBarker commented
If I recall correctly from when I set it up on my own repository, you should be able to go to the pages tab in the repository settings page, and select the source to be from Github Actions.

<img width="1160" alt="Skærmbillede 2022-12-25 kl  11 53 27 PM" src="https://user-images.githubusercontent.com/53623746/209514375-976551fb-bb67-49e4-9fae-61e183eeffb9.png">

You can see above that the docs building succeeded, but the deploy failed. I *believe* (I don't have access to the logs), this is because the source isn't set to Github Pages. If you change that, I think it should work.

Thanks!

2022-12-27 08:20 UTC, kvark commented
Thanks for the info! I switched the github pages source to github actions, but the CI action still seems to be failing. Anything I'm missing?

2023-12-19 12:41 UTC, MarijnS95 requested changes
Can this be retried? It's quite annoying to have to find & jump to a custom fork to read the documentation.

Also don't forget to update `Cargo.toml` with a `documentation=` link to GitHub pages, and improve the mentions in the readme.

2023-12-19 12:41 UTC, MarijnS95 commented on .github/workflows/rust.yml
> +name: Rust
```suggestion
name: Publish Rust documentation to GitHub pages
```

And perhaps rename the file as well?

2023-12-19 12:43 UTC, MarijnS95 commented
How about updating the PR description with `Fixes #5 fixes #276`?

2025-01-29 23:12 UTC, closed without merging