chore: Fix timestamp bug and add required method
gfx-rs/metal-rs pull request #265
Opened 2023-04-01 20:38 UTC by FL33TW00D

Introduced a bug in the last PR.

2023-04-02 12:38 UTC, FL33TW00D commented on src/computepass.rs
> +            let () = msg_send![sample_buffer, retain];
I needed this `retain` to stop SEGFAULTs during wgpu implementation.
Unsure of it's validity.

https://developer.apple.com/documentation/metal/mtlcomputepasssamplebufferattachmentdescriptor/3564439-samplebuffer?language=objc

2023-04-02 13:03 UTC, madsmtm commented on src/computepass.rs
> +            let () = msg_send![sample_buffer, retain];
`retain` returns a pointer, so you should do `let _: *const Object = msg_send![sample_buffer, retain]`.

Not entirely sure why you have memory management problems, but an extra `retain` is always sound (it'll just leak if incorrect).

2023-04-04 02:53 UTC, kvark requested changes

2023-04-04 02:53 UTC, kvark commented on src/computepass.rs
> +            let () = msg_send![sample_buffer, retain];
@FL33TW00D this looks like it could be a problem on `wgpu` side. Metal shouldn't be explicitly adding this `retain`, and instead `wgpu` should keep the object alive, just like it does for any other resources referenced by command buffers.

2023-05-04 06:43 UTC, kvark approved these changes

2023-05-04 06:43 UTC, merged